### ISSUE TITLE
Create the type `Labels`, just like the http has the `Values` type

### ISSUE THREAD

**Issue by victormn** [arquivei/foundationkit#19]
Some idea for the future. Create the tye `Labes`, just like the http has the `Values` type: https://golang.org/pkg/net/url/#Values

_Originally posted by @rjfonseca in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM1NTYxNTkzMw==/comments/review_comment_

**Comment by rjfonseca** [comment]
@victormn The link to the comment is broken, do you remember what this is about?
