### ISSUE TITLE
Error trying to run examples

### ISSUE THREAD

**Issue by joesantos418** [arquivei/foundationkit#215]
I'm using Go 1.19, I cloned the project and ran the command to run the app example:

go run ./app/examples/servefiles/ -log-human -log-level=debug

I got this error:

build github.com/arquivei/foundationkit/app/examples/servefiles: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

I suspected an error with an import, so I ran go mod tidy and got this error:

github.com/arquivei/foundationkit/avroutil/example imports
     embed: malformed module path "embed": missing dot in first path element
github.com/arquivei/foundationkit/gokitmiddlewares/metricsmiddleware/v2/example imports
    github.com/prometheus/client_golang/prometheus imports
    runtime/metrics: malformed module path "runtime/metrics": missing dot in first path element
github.com/arquivei/foundationkit/trace imports
	contrib.go.opencensus.io/exporter/stackdriver imports
	go.opencensus.io/plugin/ochttp tested by
	go.opencensus.io/plugin/ochttp.test imports
	golang.org/x/net/http2 imports
	io/fs: malformed module path "io/fs": missing dot in first path element

Does anyone know what I may be doing wrong?

**Comment by rjfonseca** [comment]
I'm unable to reproduce this error. Running locally I get the expected result:

```
go run ./app/examples/servefiles/ -log-human -log-level=debug
9:08AM INF Application main loop starting now! goversion=go1.19.4 version=development
```

Please provide the output of `go version`.

**Comment by joesantos418** [comment]
So for some reason, my go is 1.13:

go version go1.13.8 linux/amd64

I'll update and try again

**Comment by joesantos418** [comment]
It works now, thanks

**Comment by rjfonseca** [comment]
❤️
